### ISSUE TITLE
More user-friendly meta info

### ISSUE THREAD

**Issue by Honno** [HarmanU/coursework-great-game-of-britain#20]
Could we change the GitHub title for this repo to `great-game-of-britain`, to make it more user readable and git-y?

Also could we change the description to the following?
```
Simulation of The Great Game of Britain board game, made in Unity.
```
I think it quickly conveys what we've done with this project, making it better for people skimming over our profiles on this site.

Totally not just wanting to play around with GH issues xD

**Comment by HarmanU** [comment]
chnaged to coursework-great-game-of-britian

**Comment by HarmanU** [comment]
re-changed to great-game-of-britain-coursework
